name: Update TOC
on:
  schedule:
    - cron: "1-59 * * * *"

jobs:
  build:
    runs-on: macos-latest
    permissions:
      issues: read
      contents: write
    steps:
      - users: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "yarn"
      - run: make setup
      - run: make build
      - run: node lib/index.js
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
